version: "3"

services:
  rubrix:
    image: recognai/rubrix:latest
    # build:
    #   context: .
    #   dockerfile: dev.Dockerfile
    restart: unless-stopped
    ports:
      - "6900:80"
    environment:
      ELASTICSEARCH: http://elasticsearch:9200
      RUBRIX_LOCAL_AUTH_USERS_DB_FILE: /config/.users.yaml
      rubrix_local_auth_default_apikey: 4AkeAPIk3Y
    volumes:
      - type: bind
        source: ./.users.yaml
        target: /config/.users.yaml
    networks:
      - rubrix

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-rubrix-local
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data:rw
    networks:
      - rubrix

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:7.11.1
  #   container_name: kibana
  #   ports:
  #     - 5601:5601
  #   environment:
  #     ELASTICSEARCH_URL: http://elasticsearch:9200
  #     ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
  #   networks:
  #     - rubrix
volumes:
  esdata1:
    driver: local
    
networks:
  rubrix:
    driver: bridge